### ISSUE TITLE
Doesn't work on Android <= 4.1.2

### ISSUE THREAD

**Issue by TimPietrusky** [micjamking/navigataur#1]
There is a problem with the [default checkbox hack](http://css-tricks.com/the-checkbox-hack/) and because Navigataur uses this hack, it doesn't work on Android <= 4.1.2. 

You can fix this by adding a fake animation to the `body`:

```
body { 
  -webkit-animation: bugfix infinite 1s; 
}
@-webkit-keyframes bugfix { 
  from {padding:0;} 
  to {padding:0;} 
}
```

Read more about this in my [Advanced Checkbox Hack](http://timpietrusky.com/advanced-checkbox-hack) article.

**Comment by micjamking** [comment]
Thanks Tim! 

I originally only tested on iOS6 & Android 4.2 because those are the device OS's I have on tap. The plugin support section is based on sibling selector support from the browser vendors (which is not completely accurate for the checkbox hack, as you've pointed out in your article :poop: )

I'll need to add your above code (along with your iOS `<label onclick></label>` hack) to the required styles for better device compatibility.

**Comment by micjamking** [comment]
The functional styles have been updated with your advanced checkbox hack and the sample html (& readme) includes the onclick attribute on the label:

```
/*--------------------------------
 Functional Styles (Required)
---------------------------------*/
/* Tim Pietrusky advanced checkbox hack (Android <= 4.1.2) */
body{ -webkit-animation: bugfix infinite 1s; }
@-webkit-keyframes bugfix { from {padding:0;} to {padding:0;} }
...
```

https://github.com/micjamking/Navigataur/blob/master/navigataur.css

Thanks!

**Comment by TimPietrusky** [comment]
Awesome! I'm Glad I could help!
