### ISSUE TITLE
ie8 support

### ISSUE THREAD

**Issue by 2dareis2do** [micjamking/navigataur#16]
Although it is possible to add ie 8 support for media queries using respond.js, I don't think the :checked pseudo class is supported in <ie9

https://developer.mozilla.org/en-US/docs/Web/CSS/:checked

**Comment by 2dareis2do** [comment]
actually I think the issue is more to do with hidden checkboxes not receiving events:

http://stackoverflow.com/questions/3072522/labels-and-hidden-fields-in-internet-explorer-and-jquery

**Comment by micjamking** [comment]
@2dareis2do I don't think providing IE8 support for small screen device usage of the plugin is practical or necessary. Are there realistic use-cases for IE8 usage on small screen/mobile devices?

If you absolutely need to support mobile / small screen views for legacy browsers, there are JavaScript solutions readily available.

**Comment by 2dareis2do** [comment]
ok, using a combination of selectivizr, formatting my css like input[type='radio']:checked, and making sure this degrades so that the checkboxes can be seen in <ie9 using repsond.js .lt-ie9 syntax as well as support for media queries, this kind of works.

can be seen in action here

metrodental.co.uk

**Comment by 2dareis2do** [comment]
yes would be good if we did not have support ie 8, but I like to keep things as consistent as possible cross browser rather than coming up with loads of exceptions. May be it does not look so good but at least the basic functionality is there. 

WIndows dropping support for xp is probably a good thing and should pave the way to dropping ie 8. still alot of people using it though, although admitably not in percentage terms.

**Comment by micjamking** [comment]
@2dareis2do I'm not negating IE8's usage; it is still here and being used frequently, especially for the enterprise & finance industry. However, Navigataur (and responsive web design as a whole) aims to provide support for a range of screen sizes, specifically sizes outside of typical desktop usage (i.e. mobile, television, etc.). Navigatuar works on desktop as is, which is 100% of all IE8 users. 

So my question is, what is the use-case for IE8 on a mobile/small-screen device? I understand the mobile menu doesn't work in IE8, but how/when would the scenario occur that an IE8 user is interacting with the mobile version of a site?

Nice work on the website btw :)

**Comment by 2dareis2do** [comment]
My approach is to make the desktop responsive. That way we can cater for all different devices without having to optimize for specific 'smartphone' and tablet devices.

So wanting ie8 to respond is for the same reasons as you might want your modern desktop browser to respond. It simply means that we can have a site that looks consistent and works cross browser without having to make ie specific stylesheets and make difficult design tweaks/compromises  just for ie8 etc.

**Comment by micjamking** [comment]
@2dareis2do I suppose this is where we fundamentally disagree.

> _So wanting ie8 to respond is for the same reasons as you might want your modern desktop browser to respond._

These are not the same. I want a modern browser to respond because modern browsers can be utilized on modern devices of different resolutions and aspect ratios. This is not the same environment as a 5 year old browser with [less than 5% market share](http://www.w3counter.com/globalstats.php). Is there any research that supports the argument of IE8 users accessing the web on screen small devices?

> _It simply means that we can have a site that looks consistent and works cross browser without having to make ie specific stylesheets and make difficult design tweaks/compromises just for ie8 etc._

I understand this in concept, but it's just not realistic. Supporting legacy browsers is a compromise if your aim is to build for modern devices. [This is the reason why some front-end frameworks simply don't support IE8 & below](http://foundation.zurb.com/learn/faq.html#question-1).  

You said yourself that you had to use a combination of selectivizr, respond.js, & an IE specific stylesheet to support your site. Which means IE8 users are getting a heavier, slower site to support those modern features. You may achieve  a consistent look, but this will ultimately have an impact on the user experience.

I completely understand if you need to support IE8 for client work, there's no argument against that. My only point is that Navigataur (or any css-only plugin) is not the right option if you need IE8 support. If you are already going to conditionally load javascript just to support this plugin, why not use one of the [many responsive navigation jquery plugins available](http://speckyboy.com/2013/08/01/15-responsive-navigation-jquery-plugins/) instead.
