### ISSUE TITLE
Retina friendly?

### ISSUE THREAD

**Issue by jackmcconnell** [micjamking/navigataur#3]
Love this method, really handy. 

I have one small issue though: 
I've replaced the content CSS property with an image URL showing a list icon when closed and a cross when open. This works great but in order for it to be retina friendly, I need to replace the 1x image with the 2x retina version. When doing this however, it just shows at double the size as I can't set the background-size. Do you have any suggestions on how I might be able to provide a retina version of the image to the toggle? 

Thanks!

**Comment by micjamking** [comment]
Hmmm... I see what your saying. 

Have you tried using the `.toggle:before` element's background, that way you still have access to the `background-size` property? 

You would need to remove the `.toggle:after` pseudo elements content property (or more accurately, make the property empty, ie. `content: ''`), and give the `.toggle:before` pseudo element a higher z-index so that it sits on top of the `.toggle:after` element (or switch them around might be better).

It's all a part of the presentational styling, so you can basically edit it as you see fit. Hope this helps.

Thanks,
Mike

**Comment by jackmcconnell** [comment]
Thanks for replying Mike, 

I'm a bit lost with what you're saying though, if I showed you my code would you be able to give me a better idea of what you mean?

**Comment by micjamking** [comment]
Sure, can you try uploading your code to [codepen.io](http://codepen.io)? That way I can check it out and make changes if needed. Thanks!

**Comment by jackmcconnell** [comment]
Thanks Mike, 

Here's a link to the code: http://cdpn.io/zDrld

**Comment by micjamking** [comment]
Hey Voltronik,

Try this out: [http://cdpn.io/nsdtF](http://cdpn.io/nsdtF)

Basically, I'm using the `background` property instead of `content`, so that it works with `background-size` for your retina media query.

Ideally, you should look at using an icon font since fonts are a vector format, and therefore, will be crisp on any screen resolution. You only need to update the `font-size` property for legibility on different screen sizes (plus, you can still use the `content` property).

Here's a really exhaustive list of some icon fonts if your interested in checking it out:

[CSS-Tricks: The Big List of Flat Icons & Icon Fonts](http://css-tricks.com/flat-icons-icon-fonts/)

Hope this helps.
- Mike

**Comment by jackmcconnell** [comment]
Hi Mike, 

That's perfect! Had a bit of a play and got it working perfectly. 
Thank you for pointing me in the right direction.
